version: '3'

services:
  app:
    image: node:lts # バージョン指定も可能 ex. node:12.16.1
    container_name: threeJs
    tty: true
    volumes:
      - ./src:/src
    working_dir: "/src"
    ports:
      - "8080:3000"